name: Build Multiplatform project
on:
  push:
    branches:
      - sudo
#      - main
#      - feature/ci_support
  pull_request:

jobs:
  build-multiplatform-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        gradle: [8.3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'
      - name: Build Multiplatform project
        shell: bash
        run: ./gradlew assemble