name: Check code style
on:
  push:
    branches:
      - sudo
#      - main
#      - feature/ci_support
  pull_request:

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'jetbrains'
          java-version: '21'
      - name: Check code style
        shell: bash
        run: ./gradlew ktlintCheck