name: Check code style
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'
      - name: Check code style
        shell: bash
        run: ./gradlew spotlessCheck