name: Publish Wiki
on:
  push:
    branches:
      - sudo
#      - main
    paths-ignore:
      - sample

concurrency:
  group: publish-wiki
  cancel-in-progress: true

jobs:
  publish-wiki:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Wiki
        run: ./gradlew library:dokkaGeneratePublicationHtml

      - name: Upload Wiki
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./library/build/dokka
          branch: gh-pages
          force: true